REPORT ZPROGHANA_02.

TABLES SFLIGHT.

SELECT-OPTIONS S_CARRID FOR SFLIGHT-CARRID.

* Tipo
TYPES: BEGIN OF ty_sflight,
        CARRID TYPE SFLIGHT-CARRID,
        CONNID TYPE SFLIGHT-CONNID,
        FLDATE TYPE SFLIGHT-FLDATE,
      END OF TY_sflight.

* WorkArea
DATA LS_SFLIGHT TYPE TY_SFLIGHT.

* Tabela Interna
DATA LT_SFLIGHT TYPE TABLE OF TY_SFLIGHT.

* Seleciona Dados
SELECT CARRID
       CONNID
       FLDATE
       FROM SFLIGHT
       INTO TABLE LT_SFLIGHT
       WHERE CARRID IN S_CARRID.

* Imprimindo Dados
LOOP AT LT_SFLIGHT INTO LS_SFLIGHT.

  WRITE: / LS_SFLIGHT-CARRID,
           LS_SFLIGHT-CONNID,
           LS_SFLIGHT-FLDATE.

ENDLOOP.
