REPORT ZPROGHANA_01

* Selecionando DADOS
SELECT CARRID,
       CONNID,
       FLDATE
       FROM SFLIGHT
       INTO TABLE @DATA(LT_SFLIGHT).

* Imprimindo DADOS
LOOP AT LT_SFLIGHT INTO DATA(LS_SFLIGHT).
  WRITE: / LS_SFLIGHT-CARRID,
           LS_SFLIGHT-CONNID,
           LS_SFLIGHT-FLDATE.
ENDLOOP.
